---
# tasks file for roles/postgres

## PREREQUISITES #################################################################################

#- name: install libselinux-python
#  yum: name={{ item }} state=present
#  with_items:
#   - libselinux-python
#   - epel-release
#  tags: ['install']

#- name: install python-pip
#  yum: name=python-pip state=present
#  tags: ['install']

#- name: install pexpect
#  pip: name=pexpect state=latest
#  tags: ['install']

## POSTGRESQL INSTALLATION ######################################################################
- name: copy postgres rpm
  copy: src=pgdg-centos93-9.3-3.noarch.rpm dest=/home/devops/ mode=0755    
  tags: ['install']

- name: install postgres rpm
  yum: name="{{ path_postgres_rpm }}" state=present
  tags: ['install']

- name: pause for 1 min
  pause:
    minutes: 1

- name: install postgres
  yum: name={{ postgresql_version }} state=present
  tags: ['install']

- name: Initiate database
  command: service "{{ postgresql_service }}" initdb creates={{ postgresql_conf_path }}/postgresql.conf
  tags: ['configure']

- name: Start PostgreSQL and enable at boot
  service: name="{{ postgresql_service }}" enabled=yes state=started
  tags: ['configure']

- name: Update pg_hba.conf
  template: src=pg_hba.conf dest={{ postgresql_conf_path }} mode=0644
  notify: restart postgresql
  tags: ['configure']

- name: Update postgresql.conf
  template: src=postgresql.conf dest={{ postgresql_conf_path }} mode=0644
  notify: restart postgresql
  tags: ['configure']

#- name: Update iptables
#  lineinfile: dest=/etc/sysconfig/iptables regexp='-A INPUT -m state --state NEW -m tcp -p tcp --dport 5432 -j ACCEPT'
#              line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 5432 -j ACCEPT' insertbefore='INPUT -j REJECT*'
#  notify: restart iptables    
#  tags: ['configure']

## SCHEMA ###########################################################################################
- include_vars: inventory/group_vars/postgres-server/postgres-pwd.yml
  tags: ['schema']

- name: restart postgresql 
  service: name={{ postgresql_service }} state=restarted
  tags: ['schema']

- name: install python-psycopg2
  yum: name=python-psycopg2 state=present
  tags: ['schema']

- name: Change postgres password 
  postgresql_user: db=postgres user=root login_user=postgres password={{ pg_user_password }}
  notify: restart postgresql
  tags: ['schema']

- name: Create database
  postgresql_db: name={{ dbname }} state=present login_password={{ pg_db_password }}
  tags: ['schema']

- name: Create user
  postgresql_user: db={{ dbname }} name={{ dbuser }} password={{ pg_db_password }} priv= "ALL/{{ dbtable }}:ALL" login_password={{ pg_user_password }}
  notify: restart postgresql
  tags: ['schema']

- name: Transfer the script
  copy: src={{ sql_script }} dest=/home/devops mode=0777
  tags: ['schema']

- name: Execute create table script
  command: /usr/bin/psql -f /home/devops/{{ sql_script }} -d "{{ dbname }}"
  environment:
     PGUSER: "{{ dbuser }}"
     PGDATABASE: "{{ dbname }}"
     PGPASS: "{{ pg_db_password }}"
  tags: ['schema']

- name: remove sql script file
  file: path=/home/devops/{{ sql_script }} state=absent
  tags: ['schema']

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{ pg_db_password }} priv=ALL login_password={{ pg_user_password }}
  notify: restart postgresql
  tags: ['schema']
